name: "Wagner Leonardi"
description: "software engineer"
avatar: /assets/images/me.png
title: "Wagner Leonardi"

author:
  twitter:          leonardiwagner
  github:           leonardiwagner
  stackoverflow:    wagner-leonardi
  linkedin:         leonardiwagner
  email:            leonardiwagner@gmail.com

copyright:
  year:             2020
  name:             Wagner Leonardi

# Google-analytics
google_analytics: "95146900"

# Disqus
disqus: "wagnerleonardi"

# URL
url:                "http://wagnerleonardi.com" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Sao_Paulo
permalink:          /:title/

# Pagination
paginate:           10
paginate_path:      /page:num/

# Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Navigation
nav:
  - name:           "LinkedIn"
    url:            "https://www.linkedin.com/in/leonardiwagner"
  - name:           "GitHub"
    url:            "https://github.com/leonardiwagner"
  - name:           "About"
    url:            "/about"

# Sass
sass:
  sass_dir:         _sass
  style:            :expanded

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  

exclude:
  - LICENSE
  - README.md
  - CNAME

# Includes an icon in the footer for each username you enter
footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email:
  facebook:
  flickr:
  github: AWEEKJ/kiko-now
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  twitter: jekyllrb
  youtube: # channel/<your_long_string> or user/<user-name>

# Text under the icons in footer
footer-text: © 2017 Kiko Now