# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wagner Leonardi - Software Engineer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Wagner, a description is comming!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.wagnerleonardi.com" # the base hostname & protocol for your site
twitter_username: leonardiwagner
github_username:  leonardiwagner

# Build settings
markdown: kramdown

# Outputting
permalink:     /:title