
# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Wagner Leonardi"

author:
  twitter:          your-id
  github:           your-id
  stackoverflow:    your-id

  linkedin:         your-id

  email:            leonardiwagner@gmail.com

copyright:
  year:             2017
  name:             Wagner Leonardi

# Google-analytics
google-analytics:
  id:               "95146900"

# Disqus
disqus:
  id:               "wagnerleonardi"

# URL
url:                "http://wagnerleonardi.com" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/Sao_Paulo
permalink:          /:title/

# Pagination
paginate:           10
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "linkedin"
    url:            "https://www.linkedin.com/in/wagner-leonardi-801aa179/"
  - name:           "Github"
    url:            "https://github.com/leonardiwagner"
  - name:           "StackOverflow"
    url:            "https://stackoverflow.com/users/1778285/wagner-leonardi"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]